### ISSUE TITLE
Push docker image of Apache in Ubuntu 15.10

### ISSUE THREAD

**Issue by paulobezerr** [phalcon/dockerfiles#17]
Push image of [Apache in Ubuntu 15.10](https://github.com/phalcon/dockerfiles/tree/master/php-apache/ubuntu-15.10) to [Docker Hub](https://hub.docker.com/r/phalconphp/php-apache/)

**Comment by sergeyklay** [comment]
Well, the image here https://hub.docker.com/r/phalconphp/php-apache/tags/

But actually there is some minor error like
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/weakref.so'
```

and 

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/handlersocketi.so'
```

I'll try to sort out. But I have no idea when. If anyone wants to get started, I'd love that.
