### ISSUE TITLE
Include dev-tools by default

### ISSUE THREAD

**Issue by igorbarkowsky** [phalcon/dockerfiles#23]
Proposal to include phalcon dev-tools by default into images.

**Comment by sergeyklay** [comment]
A lot of of the Docker images located in the `phalconphp/dockerfiles` repository are educational and/or experimental. In addition, these Docker images need a maintainer as well as constant updating. We would like to leave in this repository only those Docker images that we need to build DEBs and RPMs: https://github.com/phalcon/dockerfiles/tree/master/build  I recommend you to create your own Docker images that meets your needs. Please feel free to ask any questions regarding creating own Docker images.
