### ISSUE TITLE
error 503 when deploying on VPS

### ISSUE THREAD

**Issue by Ridder90** [phalcon/dockerfiles#24]
Hi There, 

When bringing up the project on a vps. I get an error 503. No errors or hints shown. The vps is running on a freashly installed `ubuntu 16.04 LTS` with `Docker version 18.03.0-ce` and `docker-compose version 1.20.1`.  

I noticed there is a core file dumped in the public folder. Is this something i can use to debug it?

```
app_1            | [Thu Mar 29 09:52:42.937281 2018] [proxy_fcgi:error] [pid 406:tid 139817385203456] [client 31.160.154.217:63404] AH01067: Failed to read FastCGI header
app_1            | [Thu Mar 29 09:52:42.937396 2018] [proxy_fcgi:error] [pid 406:tid 139817385203456] (104)Connection reset by peer: [client 31.160.154.217:63404] AH01075: Error dispatching request to : 
app_1            | docker.vm:443 31.160.154.217 - - [29/Mar/2018:09:52:42 +0000] "GET / HTTP/1.1" 503 2850 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"
app_1            | [httpd:access] lsa.deriddercode.nl:443 31.160.154.217 - - [29/Mar/2018:09:52:42 +0000] "GET / HTTP/1.1" 503 bytesIn:835 bytesOut:2850 reqTime:0
app_1            | [29-Mar-2018 09:52:42] WARNING: [pool www] child 633 exited on signal 4 (SIGILL - core dumped) after 57.375197 seconds from start
app_1            | [29-Mar-2018 09:52:42] NOTICE: [pool www] child 668 started
```

Thanks in advance

**Comment by toolowner** [comment]
I got the same error

**Comment by thiagovictorino** [comment]
I got this error in my local Macbook machine

**Comment by sergeyklay** [comment]
Could you please provide docker image name and version

**Comment by sergeyklay** [comment]
A lot of of the Docker images located in the `phalconphp/dockerfiles` repository are educational and/or experimental. In addition, these Docker images need a maintainer as well as constant updating. We would like to leave in this repository only those Docker images that we need to build DEBs and RPMs: https://github.com/phalcon/dockerfiles/tree/master/build  I recommend you to create your own Docker images that meets your needs. Please feel free to ask any questions regarding creating own Docker images.
