### ISSUE TITLE
Why does nginx run as a seperate container?

### ISSUE THREAD

**Issue by JamesArthurHolland** [phalcon/dockerfiles#30]
I don't understand why nginx runs as a seperate container. What happens if I have multiple PHP microservices in the same cluster? 

There will be multiple nginx containers when there doesn't need to be. I don't think this seperates concerns well. I think nginx should ship inside the phalcon container.

**Comment by Jeckerson** [comment]
You can do your own Dockerfile with php + nginx as single container... Here are just examples.
