### ISSUE TITLE
phalconphp/php-fpm:5.6 docker image installs PHP7.2

### ISSUE THREAD

**Issue by JamesArthurHolland** [phalcon/dockerfiles#31]
I've been trying for nearly a week to get phalcon and nginx running on kubernetes. I'm getting this coredump issue with versions 7.*

https://github.com/phalcon/cphalcon/issues/13255

Also, when I use the phalconphp/php-fpm:5.6 image, it installs:
$ php --version
PHP 7.2.1 (cli) (built: Jan  8 2018 23:39:24) ( NTS )

This seems wrong?

**Comment by sergeyklay** [comment]
@JamesArthurHolland Could you please remove `-march=native -mtune=native`, recompile Phalcon and test again?

https://github.com/phalcon/cphalcon/blob/caeac66e7db02fd54c44a27cf22a6381654af2ee/build/install#L27
